// Media
export const SET_ALL_MEDIA = 'SET_ALL_MEDIA';
export const SET_COUNT = 'SET_COUNT';
export const SET_MEDIA_LOADING = 'SET_MEDIA_LOADING';
export const SET_CURRENT_NOTIFICATION = 'SET_CURRENT_NOTIFICATION';
export const SET_LOADING_NOTIFICATION = 'SET_LOADING_NOTIFICATION';
export const SET_MEDIA_BADGE = 'SET_MEDIA_BADGE';